name: pos_system
description: A POS system built with Flutter and Firebase using GetX.
publish_to: 'none' 
version: 1.0.0+1
environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
    
  firebase_core: ^2.24.2
  firebase_auth: ^4.15.3
  cloud_firestore: ^4.13.6
  firebase_storage: ^11.5.6
  firebase_messaging: ^14.7.9
  firebase_analytics: ^10.7.4
  firebase_crashlytics: ^3.4.8

  cupertino_icons: ^1.0.2
  get: ^4.6.6
  get_storage: ^2.1.1
  barcode_scan2: ^4.5.1
  flutter_stripe: ^11.5.0
  intl: ^0.20.2
  uuid: ^4.2.2
  flutter_charts: ^0.5.2
  image_picker: ^1.0.7
  path_provider: ^2.1.1
  permission_handler: ^12.0.0+1
  flutter_local_notifications: ^19.1.0
  connectivity_plus: ^6.1.4
  cached_network_image: ^3.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0
  build_runner: ^2.4.7
  firebase_core_platform_interface: ^5.4.0

flutter:

  uses-material-design: true

  assets:
    - assets/images/
    - assets/icons/